# Generated by Django 5.2.8 on 2026-09-05 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('account_type', models.CharField(choices=[('cash', 'Caja'), ('bank', 'Banco'), ('digital', 'Saldo digital')], db_index=True, max_length=16, verbose_name='Tipo')),
                ('opening_balance', models.DecimalField(decimal_places=0, default=0, help_text='Punto de partida. El saldo actual se calcula a partir de los movimientos.', max_digits=14, verbose_name='Saldo inicial (CLP)')),
                ('opening_balance_date', models.DateField(verbose_name='Fecha del saldo inicial')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Cuenta de tesorería',
                'verbose_name_plural': 'Cuentas de tesorería',
                'ordering': ['account_type', 'name'],
                'permissions': [('view_finance', 'Puede ver el módulo Finanzas'), ('add_manual_sale', 'Puede registrar venta física'), ('register_expense', 'Puede registrar gastos'), ('manage_financing', 'Puede gestionar financiamiento'), ('manage_accounts', 'Puede gestionar cuentas de tesorería'), ('manage_purchases', 'Puede gestionar compras'), ('manage_catalog', 'Puede gestionar catálogo e inventario')],
                'indexes': [models.Index(fields=['account_type', 'is_active'], name='finance_fin_account_808798_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__gt', '')), name='finance_account_name_not_empty')],
            },
        ),
    ]
