# Generated by Django 5.2.8 on 2026-09-05 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_finance_foundation'),
        ('shop', '0027_payment_settlement_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='ledger_role',
            field=models.CharField(blank=True, choices=[('mp', 'Liquidaciones Mercado Pago'), ('bank_transfers', 'Transferencias bancarias'), ('cash', 'Caja efectivo')], help_text='Como máximo una cuenta por rol. Las liquidaciones MP usan el rol Mercado Pago.', max_length=32, null=True, unique=True, verbose_name='Rol en tesorería'),
        ),
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Monto bruto (CLP)')),
                ('fee_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Comisión real (CLP)')),
                ('net_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Monto liquidado (CLP)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de liquidación'), ('settled', 'Liquidado'), ('voided', 'Anulado')], db_index=True, default='pending', max_length=16, verbose_name='Estado')),
                ('settled_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de liquidación')),
                ('money_release_date', models.DateField(blank=True, null=True, verbose_name='Fecha de liberación MP')),
                ('mp_payment_id', models.CharField(db_index=True, max_length=100, verbose_name='MP Payment ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='finance.financialaccount', verbose_name='Cuenta destino')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='shop.order', verbose_name='Pedido')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='shop.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Liquidación de pago',
                'verbose_name_plural': 'Liquidaciones de pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=8, verbose_name='Dirección')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Monto (CLP)')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='Fecha económica')),
                ('movement_type', models.CharField(choices=[('sale_settlement', 'Liquidación de venta'), ('manual_adjustment', 'Ajuste manual')], db_index=True, max_length=32, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmado'), ('voided', 'Anulado')], db_index=True, default='confirmed', max_length=16, verbose_name='Estado')),
                ('origin', models.CharField(choices=[('automatic', 'Automático'), ('manual', 'Manual')], default='automatic', max_length=16, verbose_name='Origen')),
                ('idempotency_key', models.CharField(max_length=120, unique=True, verbose_name='Clave de idempotencia')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.financialaccount', verbose_name='Cuenta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='shop.order', verbose_name='Pedido')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='shop.payment', verbose_name='Pago')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='finance.paymentsettlement', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Movimiento de tesorería',
                'verbose_name_plural': 'Movimientos de tesorería',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentsettlement',
            constraint=models.UniqueConstraint(fields=('mp_payment_id',), name='unique_settlement_mp_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='paymentsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='settlement_gross_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='paymentsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='settlement_fee_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='paymentsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='settlement_net_gte_0'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['account', 'occurred_on'], name='finance_fin_account_7a900c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['status', 'occurred_on'], name='finance_fin_status_a15ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['movement_type', 'occurred_on'], name='finance_fin_movemen_4e36f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='movement_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key__gt', '')), name='movement_idempotency_not_empty'),
        ),
    ]
