# Generated by Django 5.2.8 on 2026-09-05 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_settlement_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale_settlement', 'Liquidación de venta'), ('manual_adjustment', 'Ajuste manual'), ('capital_contribution', 'Aporte de capital'), ('loan_in', 'Desembolso de préstamo'), ('loan_repayment', 'Pago de préstamo')], db_index=True, max_length=32, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contribution', 'Aporte de capital'), ('loan', 'Préstamo')], db_index=True, max_length=16, verbose_name='Tipo')),
                ('counterparty', models.CharField(max_length=160, verbose_name='Origen / prestamista')),
                ('principal', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Monto original (CLP)')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financings', to='finance.financialaccount', verbose_name='Cuenta destino')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financings', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Financiamiento',
                'verbose_name_plural': 'Financiamientos',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='financing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.financing', verbose_name='Financiamiento'),
        ),
        migrations.AddConstraint(
            model_name='financing',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='financing_principal_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='financing',
            constraint=models.CheckConstraint(condition=models.Q(('counterparty__gt', '')), name='financing_counterparty_not_empty'),
        ),
    ]
