# Generated by Django 5.2.8 on 2026-09-05 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financing'),
        ('shop', '0027_payment_settlement_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale_settlement', 'Liquidación de venta'), ('manual_adjustment', 'Ajuste manual'), ('capital_contribution', 'Aporte de capital'), ('loan_in', 'Desembolso de préstamo'), ('loan_repayment', 'Pago de préstamo'), ('purchase', 'Compra de mercadería')], db_index=True, max_length=32, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='MerchandisePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=160, verbose_name='Proveedor')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='Fecha')),
                ('updates_stock', models.BooleanField(default=True, help_text='Si está activo, las unidades compradas entran al inventario.', verbose_name='Sumar al stock')),
                ('updates_catalog_cost', models.BooleanField(default=True, help_text='Costo estándar / último conocido. No recalcula ventas ya sincronizadas.', verbose_name='Actualizar costo vigente')),
                ('is_vat_affected', models.BooleanField(default=True, verbose_name='Afecta a IVA')),
                ('gross_total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total bruto (CLP)')),
                ('net_total', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total neto (CLP)')),
                ('vat_credit', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='IVA crédito (CLP)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='finance.financialaccount', verbose_name='Cuenta que paga')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Compra de mercadería',
                'verbose_name_plural': 'Compras de mercadería',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.merchandisepurchase', verbose_name='Compra'),
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Producto (snapshot)')),
                ('variant_label', models.CharField(blank=True, default='', max_length=64, verbose_name='Opción (snapshot)')),
                ('sku_snapshot', models.CharField(blank=True, default='', max_length=64, verbose_name='SKU (snapshot)')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_cost_net', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Costo unitario neto')),
                ('unit_cost_gross', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Costo unitario bruto')),
                ('line_net', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Neto línea')),
                ('line_gross', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Bruto línea')),
                ('line_vat', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='IVA línea')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='shop.product', verbose_name='Producto')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='shop.productvariant', verbose_name='Variante')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.merchandisepurchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Línea de compra',
                'verbose_name_plural': 'Líneas de compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='merchandisepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('supplier__gt', '')), name='purchase_supplier_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='merchandisepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('gross_total__gte', 0)), name='purchase_gross_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='purchase_line_qty_gte_1'),
        ),
    ]
