# Generated by Django 5.2.8 on 2026-09-05 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('finance', 'ExpenseCategory')
    defaults = [
        ('arriendo', 'Arriendo / local', 'infrastructure', 10),
        ('servicios', 'Servicios', 'services', 20),
        ('publicidad', 'Publicidad', 'ads', 30),
        ('otros', 'Otros', 'other', 40),
    ]
    for slug, name, kind, sort_order in defaults:
        ExpenseCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'kind': kind, 'sort_order': sort_order, 'is_active': True},
        )


def unseed_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('finance', 'ExpenseCategory')
    ExpenseCategory.objects.filter(slug__in=['arriendo', 'servicios', 'publicidad', 'otros']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_merchandise_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale_settlement', 'Liquidación de venta'), ('manual_adjustment', 'Ajuste manual'), ('capital_contribution', 'Aporte de capital'), ('loan_in', 'Desembolso de préstamo'), ('loan_repayment', 'Pago de préstamo'), ('purchase', 'Compra de mercadería'), ('expense', 'Gasto operativo')], db_index=True, max_length=32, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('kind', models.CharField(choices=[('infrastructure', 'Infraestructura'), ('services', 'Servicios'), ('ads', 'Publicidad'), ('other', 'Otros')], db_index=True, max_length=20, verbose_name='Grupo')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__gt', '')), name='expense_category_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=160, verbose_name='Proveedor / destinatario')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='Fecha')),
                ('is_vat_affected', models.BooleanField(default=True, verbose_name='Afecta a IVA')),
                ('gross_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Total bruto (CLP)')),
                ('net_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Neto (opex)')),
                ('vat_credit', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='IVA crédito (CLP)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.financialaccount', verbose_name='Cuenta que paga')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Gasto operativo',
                'verbose_name_plural': 'Gastos operativos',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.operationalexpense', verbose_name='Gasto'),
        ),
        migrations.AddConstraint(
            model_name='operationalexpense',
            constraint=models.CheckConstraint(condition=models.Q(('vendor__gt', '')), name='expense_vendor_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='operationalexpense',
            constraint=models.CheckConstraint(condition=models.Q(('description__gt', '')), name='expense_description_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='operationalexpense',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gt', 0)), name='expense_gross_gt_0'),
        ),
        migrations.RunPython(seed_expense_categories, unseed_expense_categories),
    ]
