# Generated by Django 5.2.8 on 2026-09-05 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_operational_expense'),
        ('shop', '0027_payment_settlement_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale_settlement', 'Liquidación de venta'), ('manual_adjustment', 'Ajuste manual'), ('capital_contribution', 'Aporte de capital'), ('loan_in', 'Desembolso de préstamo'), ('loan_repayment', 'Pago de préstamo'), ('purchase', 'Compra de mercadería'), ('expense', 'Gasto operativo'), ('shipment', 'Flete de envío'), ('refund', 'Devolución al cliente')], db_index=True, max_length=32, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='Fecha')),
                ('restores_stock', models.BooleanField(default=True, verbose_name='Devolver stock')),
                ('gross_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Bruto devuelto')),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Neto devuelto')),
                ('vat_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='IVA revertido')),
                ('cogs_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Costo revertido')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.financialaccount', verbose_name='Cuenta que devuelve el dinero')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='shop.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.orderrefund', verbose_name='Devolución'),
        ),
        migrations.CreateModel(
            name='OrderRefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('gross_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Bruto')),
                ('net_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Neto')),
                ('vat_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='IVA')),
                ('cogs_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Costo')),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Comisión revertida')),
                ('shipping_assumed_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Flete revertido')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_lines', to='shop.orderitem', verbose_name='Línea original')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.orderrefund', verbose_name='Devolución')),
            ],
            options={
                'verbose_name': 'Línea de devolución',
                'verbose_name_plural': 'Líneas de devolución',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, default='', max_length=120, verbose_name='Courier')),
                ('tracking_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Seguimiento')),
                ('charged_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Cobrado al cliente')),
                ('actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Costo real (courier)')),
                ('assumed_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Costo asumido (margen)')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='finance.financialaccount', verbose_name='Cuenta que paga el flete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='shop.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.ordershipment', verbose_name='Envío'),
        ),
        migrations.AddConstraint(
            model_name='orderrefund',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='refund_gross_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderrefunditem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='refund_item_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ordershipment',
            constraint=models.CheckConstraint(condition=models.Q(('charged_amount__gte', 0)), name='shipment_charged_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ordershipment',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost__gte', 0)), name='shipment_actual_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ordershipment',
            constraint=models.CheckConstraint(condition=models.Q(('assumed_cost__gte', 0)), name='shipment_assumed_gte_0'),
        ),
    ]
