# Generated by Django 5.2.8 on 2025-11-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cartitem_unique_together_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='Número menor = aparece primero. Solo se muestran los 3 primeros. Usar 0 para no mostrar en más vendidos.', verbose_name='Orden en más vendidos'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_order',
            field=models.IntegerField(default=0, help_text='Número menor = aparece primero. Solo se muestran los 3 primeros. Usar 0 para no mostrar en ofertas.', verbose_name='Orden en ofertas'),
        ),
    ]
