# Generated by Django 5.2.8 on 2026-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_paymentmethod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones adicionales'),
        ),
    ]
