# Generated by Django 5.2.8 on 2026-01-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_featured_order_product_offer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_init_point',
            field=models.URLField(blank=True, null=True, verbose_name='MP Init Point'),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_last_event_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último evento MP'),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MP Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MP Payment Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MP Preference ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_committed',
            field=models.BooleanField(default=False, verbose_name='Stock descontado (MP)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pending_payment', 'Pendiente de pago'), ('confirmed', 'Confirmado'), ('preparing', 'Preparando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
