# Generated by Django 5.2.8 on 2026-02-16 21:09

from django.db import migrations, models


def migrate_order_statuses(apps, schema_editor):
    """Migra los estados antiguos a los nuevos"""
    Order = apps.get_model('shop', 'Order')
    
    # Convertir 'pending' a 'realized'
    Order.objects.filter(status='pending').update(status='realized')
    
    # Convertir 'preparing' a 'confirmed' (el admin puede actualizar después según corresponda)
    Order.objects.filter(status='preparing').update(status='confirmed')


def reverse_migrate_order_statuses(apps, schema_editor):
    """Revierte la migración de estados"""
    Order = apps.get_model('shop', 'Order')
    
    # Revertir 'realized' a 'pending'
    Order.objects.filter(status='realized').update(status='pending')
    
    # Revertir 'confirmed' a 'preparing' (solo los que eran 'preparing' antes)
    # Nota: No podemos distinguir cuáles eran 'preparing', así que revertimos todos los 'confirmed'
    # Esto es una limitación de la reversión
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_shipping_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('realized', 'Realizado'), ('pending_payment', 'Pendiente de pago'), ('confirmed', 'Confirmado'), ('shipped', 'Enviado'), ('ready_for_pickup', 'Listo para Retiro'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='realized', max_length=20, verbose_name='Estado'),
        ),
        migrations.RunPython(migrate_order_statuses, reverse_migrate_order_statuses),
    ]
