# Generated by Django 5.2.8 on 2026-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_promotionbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Texto promocional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, help_text='Número menor = aparece primero. Usar 0 para no mostrar.', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Franja Promocional',
                'verbose_name_plural': 'Franjas Promocionales',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PromotionBanner',
        ),
    ]
