# Generated by Django 5.2.8 on 2026-03-01 22:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_promotionalbanner_delete_promotionbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (CLP)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_process', 'En proceso'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_type', models.CharField(choices=[('transfer', 'Transferencia Bancaria'), ('mercado_pago', 'Mercado Pago'), ('cash', 'Efectivo'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de pago')),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='MP Payment ID')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='MP Preference ID')),
                ('mp_init_point', models.URLField(blank=True, null=True, verbose_name='MP Init Point')),
                ('mp_status_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='MP Status Detail')),
                ('transfer_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia/Número de transferencia')),
                ('transfer_bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('transfer_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de cuenta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order', verbose_name='Pedido')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.paymentmethod', verbose_name='Método de pago')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
