# Generated by Django 5.2.8 on 2026-03-20 01:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.IntegerField(default=0, help_text='La regla aplica si el subtotal del carrito es mayor o igual a este monto.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto mínimo del pedido (CLP)')),
                ('region', models.CharField(blank=True, default='', help_text='Opcional. Debe coincidir con la región del cliente (texto exacto del listado). Vacío = cualquier región.', max_length=100, verbose_name='Región')),
                ('comuna', models.CharField(blank=True, default='', help_text='Opcional. Si se indica, debe coincidir con la comuna del cliente. Vacío = cualquier comuna de la región.', max_length=100, verbose_name='Comuna')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de envío (CLP)')),
                ('priority', models.IntegerField(default=0, help_text='Desempate: mayor valor gana si hay empate en especificidad y monto mínimo.', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shop.shippingmethod', verbose_name='Método de envío')),
            ],
            options={
                'verbose_name': 'Regla de envío',
                'verbose_name_plural': 'Reglas de envío',
                'ordering': ['shipping_method', '-min_order_amount', 'region', 'comuna'],
            },
        ),
    ]
