# Generated by Django 5.2.8 on 2026-03-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_seed_shipping_region_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stock_committed',
            field=models.BooleanField(default=False, help_text='True cuando el stock ya se descontó al crear el pedido (transferencia y Mercado Pago).', verbose_name='Stock descontado del inventario'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='region',
            field=models.CharField(blank=True, default='', help_text='Opcional. Copiar el nombre exacto del listado de checkout (ej. desde regiones_comunas.json). Vacío = resto de regiones.', max_length=100, verbose_name='Región'),
        ),
    ]
