# Generated by Django 5.2.8 on 2026-03-28 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q, Sum


def seed_variants_from_available_sizes(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    ProductVariant = apps.get_model('shop', 'ProductVariant')
    CartItem = apps.get_model('shop', 'CartItem')

    for product in Product.objects.all():
        raw = (product.available_sizes or '').strip()
        if not raw:
            continue
        names = [s.strip() for s in raw.split(',') if s.strip()]
        if not names:
            continue
        n = len(names)
        total = int(product.stock or 0)
        base = total // n
        rem = total % n
        for i, name in enumerate(names):
            label = name[:64]
            stock = base + (1 if i < rem else 0)
            ProductVariant.objects.get_or_create(
                product=product,
                name=label,
                defaults={'stock': stock, 'sort_order': i},
            )

    for ci in CartItem.objects.select_related('product').iterator():
        if ci.variant_id or not ci.size:
            continue
        label = (ci.size or '').strip()[:64]
        if not label:
            continue
        v = ProductVariant.objects.filter(product_id=ci.product_id, name=label).first()
        if v:
            ci.variant_id = v.id
            ci.save(update_fields=['variant'])

    # Ítems con talla/opción que no coincide con ninguna variante (catálogo cambió)
    orphan_qs = CartItem.objects.filter(variant__isnull=True).exclude(
        Q(size__isnull=True) | Q(size=''),
    )
    for ci in orphan_qs.select_related('product').iterator():
        if ProductVariant.objects.filter(product_id=ci.product_id).exists():
            ci.delete()

    # Unificar líneas duplicadas (mismo carrito + producto sin variante)
    seen_simple = {}
    for ci in CartItem.objects.filter(variant__isnull=True).order_by('id').iterator():
        key = (ci.cart_id, ci.product_id)
        if key in seen_simple:
            first = seen_simple[key]
            first.quantity = int(first.quantity) + int(ci.quantity)
            first.save(update_fields=['quantity'])
            ci.delete()
        else:
            seen_simple[key] = ci

    pids = (
        ProductVariant.objects.order_by()
        .values_list('product_id', flat=True)
        .distinct()
    )
    for pid in pids:
        total = (
            ProductVariant.objects.filter(product_id=pid).aggregate(t=Sum('stock'))['t'] or 0
        )
        Product.objects.filter(pk=pid).update(stock=total)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_stock_committed_help'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_label',
            field=models.CharField(blank=True, default='', help_text='Talla, color u otra opción al momento de la compra.', max_length=64, verbose_name='Opción (snapshot)'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Etiqueta que ve el cliente, ej: S, M, Amarilla.', max_length=64, verbose_name='Opción (talla, color, etc.)')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('sort_order', models.IntegerField(default=0, help_text='Menor número = aparece primero en el selector.', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.productvariant', verbose_name='Variante'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productvariant', verbose_name='Variante (referencia)'),
        ),
        migrations.RunPython(seed_variants_from_available_sizes, noop_reverse),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('cart', 'variant'), name='unique_cartitem_cart_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product'), name='unique_cartitem_cart_product_simple'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'name')},
        ),
    ]
