# Generated by Django 5.2.8 on 2026-03-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
