# Generated by Django 5.2.8 on 2026-04-13 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_available_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('document_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='Nº factura / ref.')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total (CLP)')),
                ('purchase_date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registro creado')),
            ],
            options={
                'verbose_name': 'Compra a proveedor',
                'verbose_name_plural': 'Compras a proveedores',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'order', 'id'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de productos'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_fee_estimate',
            field=models.IntegerField(default=0, help_text='Ej. comisión Mercado Pago; editable por pedido.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comisión pasarela estimada (CLP)'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(choices=[('web', 'Web (ecommerce)'), ('pos', 'Tienda / Manual')], default='web', max_length=8, verbose_name='Canal de venta'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_actual',
            field=models.IntegerField(default=0, help_text='Lo que usted paga al courier o en logística (para utilidad neta estimada).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Envío real pagado (CLP)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_cost_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo total línea (CLP)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_historical',
            field=models.IntegerField(default=0, help_text='Costo de mercadería al momento de la venta (no cambia si el producto cambia de costo después).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario histórico (CLP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.IntegerField(default=0, help_text='Costo de mercadería por unidad; se copia al detalle del pedido como costo histórico al vender.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario (CLP)'),
        ),
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / descripción')),
                ('category', models.CharField(choices=[('advertising', 'Publicidad'), ('fuel', 'Combustible'), ('packaging', 'Embalaje'), ('tools', 'Herramientas'), ('software', 'Software'), ('payroll', 'Sueldos'), ('fees', 'Comisiones / servicios'), ('rent', 'Arriendo'), ('other', 'Otro')], default='other', max_length=32, verbose_name='Categoría')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (CLP)')),
                ('expense_date', models.DateField(verbose_name='Fecha')),
                ('payment_method_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Método de pago (texto)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registro creado')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_expenses', to='shop.order', verbose_name='Pedido relacionado (opcional)')),
            ],
            options={
                'verbose_name': 'Gasto operacional',
                'verbose_name_plural': 'Gastos operacionales',
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_products_gross', models.IntegerField(default=0, verbose_name='Subtotal productos (bruto IVA incl.)')),
                ('discount_total', models.IntegerField(default=0, verbose_name='Descuento total')),
                ('products_after_discount_gross', models.IntegerField(default=0, verbose_name='Productos tras descuento (bruto)')),
                ('shipping_charged_gross', models.IntegerField(default=0, verbose_name='Envío cobrado (bruto IVA incl.)')),
                ('total_gross', models.IntegerField(default=0, verbose_name='Total cobrado (bruto)')),
                ('products_net', models.IntegerField(default=0, verbose_name='Productos neto (sin IVA)')),
                ('products_iva', models.IntegerField(default=0, verbose_name='IVA productos')),
                ('shipping_net', models.IntegerField(default=0, verbose_name='Envío neto (sin IVA)')),
                ('shipping_iva', models.IntegerField(default=0, verbose_name='IVA envío')),
                ('total_net_revenue', models.IntegerField(default=0, verbose_name='Ingreso neto (sin IVA)')),
                ('total_iva_output', models.IntegerField(default=0, verbose_name='IVA débito ventas (estimado)')),
                ('cogs', models.IntegerField(default=0, verbose_name='Costo mercadería vendida (CMV)')),
                ('gross_profit', models.IntegerField(default=0, verbose_name='Utilidad bruta')),
                ('net_profit_estimated', models.IntegerField(default=0, verbose_name='Utilidad neta estimada')),
                ('gross_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Margen bruto %')),
                ('net_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Margen neto %')),
                ('payment_fee_snapshot', models.IntegerField(default=0, verbose_name='Comisión (snapshot)')),
                ('shipping_actual_snapshot', models.IntegerField(default=0, verbose_name='Envío real (snapshot)')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Último cálculo')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='shop.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Resumen financiero de pedido',
                'verbose_name_plural': 'Resúmenes financieros de pedidos',
            },
        ),
    ]
