# Generated by Django 5.2.8 on 2026-04-13 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_finance_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total (CLP)')),
                ('iva_regimen', models.CharField(choices=[('iva_debito', 'Con IVA (venta o ingreso gravado) — monto total incluye IVA'), ('sin_iva', 'Sin IVA / exento — el monto es el ingreso total')], default='iva_debito', max_length=16, verbose_name='Tratamiento IVA')),
                ('income_date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registro creado')),
            ],
            options={
                'verbose_name': 'Otro ingreso',
                'verbose_name_plural': 'Otros ingresos',
                'ordering': ['-income_date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='SupplierPurchase',
        ),
        migrations.AlterModelOptions(
            name='operationalexpense',
            options={'ordering': ['-expense_date', '-id'], 'verbose_name': 'Egreso operacional', 'verbose_name_plural': 'Egresos operacionales'},
        ),
        migrations.AddField(
            model_name='operationalexpense',
            name='iva_regimen',
            field=models.CharField(choices=[('iva_credito', 'Con IVA (factura con crédito fiscal) — monto total incluye IVA'), ('sin_iva', 'Sin IVA / no afecto a crédito — el monto es el egreso total')], default='iva_credito', max_length=16, verbose_name='Tratamiento IVA'),
        ),
        migrations.AlterField(
            model_name='operationalexpense',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total (CLP)'),
        ),
        migrations.AlterField(
            model_name='operationalexpense',
            name='category',
            field=models.CharField(choices=[('advertising', 'Publicidad'), ('fuel', 'Combustible'), ('packaging', 'Embalaje'), ('tools', 'Herramientas'), ('software', 'Software'), ('payroll', 'Sueldos'), ('fees', 'Comisiones / servicios'), ('rent', 'Arriendo'), ('purchase_supplies', 'Compras / insumos / mercadería'), ('other', 'Otro')], default='other', max_length=32, verbose_name='Categoría'),
        ),
    ]
