# Generated by Django 5.2.8 on 2026-04-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_finance_ingresos_egresos_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalexpense',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderfinancialsummary',
            name='order',
        ),
        migrations.DeleteModel(
            name='OtherIncome',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_fee_estimate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sales_channel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost_actual',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_cost_total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_cost_historical',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_cost',
        ),
        migrations.DeleteModel(
            name='OperationalExpense',
        ),
        migrations.DeleteModel(
            name='OrderFinancialSummary',
        ),
    ]
