# Generated by Django 5.2.8 on 2026-04-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_operationalexpense_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_variant_badges',
            field=models.BooleanField(default=True, help_text='Si está activo y el producto tiene variantes, se muestran los cuadros de tallas/variantes sobre la imagen en el catálogo.', verbose_name='Mostrar tallas/variantes en catálogo'),
        ),
    ]
