# Generated by Django 5.2.8 on 2026-08-10 04:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_homepromomodal_orientation_images_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uses_special_shipping',
            field=models.BooleanField(default=False, help_text='Si está activo, el costo de envío a domicilio se calcula con las tarifas de región definidas abajo (productos de gran volumen).', verbose_name='Usar envío especial'),
        ),
        migrations.CreateModel(
            name='ProductShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', help_text='Copiar el nombre exacto del listado de checkout (regiones_comunas.json). Vacío = resto de regiones / tarifa por defecto.', max_length=100, verbose_name='Región')),
                ('comuna', models.CharField(blank=True, default='', help_text='Opcional. Vacío = cualquier comuna de la región.', max_length=100, verbose_name='Comuna')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de envío (CLP)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='shop.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Tarifa de envío especial',
                'verbose_name_plural': 'Tarifas de envío especial',
                'ordering': ['product', 'region', 'comuna'],
            },
        ),
    ]
