# Generated by Django 5.2.8 on 2026-09-05 05:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def fill_product_skus(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.filter(sku__isnull=True).iterator():
        Product.objects.filter(pk=product.pk).update(sku=f'MM-{product.pk}')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_folio',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='order',
            name='document_type',
            field=models.CharField(blank=True, default='', help_text='Control interno (boleta, factura, etc.). No reemplaza el SII.', max_length=32, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='order',
            name='financial_status',
            field=models.CharField(choices=[('open', 'Abierta'), ('paid', 'Pagada'), ('settled', 'Liquidada'), ('partially_refunded', 'Devuelta parcial'), ('refunded', 'Devuelta total'), ('voided', 'Anulada')], db_index=True, default='open', help_text='Estado de la venta en tesorería. Independiente del estado logístico del pedido.', max_length=20, verbose_name='Estado financiero'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_vat_affected',
            field=models.BooleanField(default=True, help_text='Si está desactivado, las líneas no calculan IVA débito.', verbose_name='Pedido afecto a IVA'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(choices=[('web', 'Web (ecommerce)'), ('pos', 'Tienda / Manual')], db_index=True, default='web', max_length=8, verbose_name='Canal de venta'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='allocation_method',
            field=models.CharField(default='net_proportional', max_length=32, verbose_name='Criterio de prorrateo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_allocated',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Comisión prorrateada'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_missing',
            field=models.BooleanField(default=True, help_text='True si al vender no había costo vigente; el margen puede estar sobreestimado.', verbose_name='Costo histórico no informado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_allocated',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Porción del descuento de pedido asignada a esta línea.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Descuento prorrateado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gross_sale',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Monto cobrado de la línea (IVA incluido si aplica). No es el precio lista.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Venta bruta efectiva'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_vat_affected',
            field=models.BooleanField(default=True, verbose_name='Línea afecta a IVA'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_cost_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo neto de la línea'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='list_unit_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio de catálogo al vender. Distinto de la venta bruta cobrada.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio lista unitario (snapshot)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='net_sale',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Venta neta'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='other_variable_allocated',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Otros costos variables prorrateados'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_assumed_allocated',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Envío asumido prorrateado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_charged_allocated',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Envío cobrado prorrateado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku_snapshot',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SKU (snapshot)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_gross_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo unitario bruto histórico'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_net_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo al momento de la venta. No se recalcula si cambia el catálogo.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo unitario neto histórico'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_debit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='IVA débito'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_gross',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo con IVA incluido, si aplica. Solo vigente; no altera márgenes históricos.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo unitario bruto vigente (CLP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_net',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo actual del catálogo. Las ventas guardan un snapshot y no se recalculan si este valor cambia.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo unitario neto vigente (CLP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vat_affected',
            field=models.BooleanField(default=True, help_text='Si está activo, las ventas de este producto se tratan como gravadas (19%).', verbose_name='Afecto a IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Identificador estable del producto. Si se deja vacío se genera MM-{id}.', max_length=64, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sales_channel', 'created_at'], name='shop_order_sales_c_aef853_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['financial_status', 'created_at'], name='shop_order_financi_d8f023_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku_snapshot'], name='shop_orderi_sku_sna_d6e556_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orderitem_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_allocated__gte', 0)), name='orderitem_discount_allocated_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('gross_sale__gte', 0)), name='orderitem_gross_sale_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('net_sale__gte', 0)), name='orderitem_net_sale_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('vat_debit__gte', 0)), name='orderitem_vat_debit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('commission_allocated__gte', 0)), name='orderitem_commission_allocated_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_assumed_allocated__gte', 0)), name='orderitem_shipping_assumed_gte_0'),
        ),
        migrations.RunPython(fill_product_skus, noop_reverse),
    ]
