# Generated by Django 5.2.8 on 2026-09-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_finance_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='finance_synced_at',
            field=models.DateTimeField(blank=True, help_text='Al primer sync se congela el costo histórico. Re-sync no lo pisa.', null=True, verbose_name='Sincronizado en finanzas'),
        ),
    ]
