# Generated by Django 5.2.8 on 2026-09-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_orderitem_finance_synced_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('mp_payment_id__isnull', False), models.Q(('mp_payment_id', ''), _negated=True)), fields=('mp_payment_id',), name='unique_payment_mp_payment_id'),
        ),
    ]
