from datetime import date
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.test import TestCase

from finance.access import user_can_access_finance
from finance.models import FinancialAccount
from shop.models import Brand, Category, CustomUser, Product


class FinanceAccessTests(TestCase):
    def test_anonymous_cannot_access(self):
        from django.contrib.auth.models import AnonymousUser

        self.assertFalse(user_can_access_finance(AnonymousUser()))

    def test_staff_without_permission_cannot_access(self):
        user = CustomUser.objects.create_user(
            email='staff@motomoto.cl',
            password='pass-12345',
            first_name='Staff',
            last_name='User',
            is_staff=True,
        )
        self.assertFalse(user_can_access_finance(user))

    def test_superuser_can_access(self):
        user = CustomUser.objects.create_superuser(
            email='admin@motomoto.cl',
            password='pass-12345',
            first_name='Admin',
            last_name='User',
        )
        self.assertTrue(user_can_access_finance(user))


class FinancialAccountTests(TestCase):
    def test_current_balance_equals_opening_balance_without_movements(self):
        account = FinancialAccount.objects.create(
            name='Caja tienda',
            account_type=FinancialAccount.AccountType.CASH,
            opening_balance=Decimal('150000'),
            opening_balance_date=date(2026, 1, 1),
        )
        self.assertEqual(account.get_current_balance(), Decimal('150000'))

    def test_clean_rejects_empty_name(self):
        account = FinancialAccount(
            name='   ',
            account_type=FinancialAccount.AccountType.BANK,
            opening_balance=Decimal('0'),
            opening_balance_date=date(2026, 1, 1),
        )
        with self.assertRaises(ValidationError):
            account.full_clean()


class ProductFinanceFieldsTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Cascos', slug='cascos')
        self.brand = Brand.objects.create(name='Shaft', slug='shaft')

    def test_sku_autogenerated_and_stable(self):
        product = Product.objects.create(
            name='Casco de prueba',
            short_description='Casco',
            description='Casco de prueba',
            category=self.category,
            brand=self.brand,
            price=119000,
            cost_net=Decimal('40000'),
            cost_gross=Decimal('47600'),
        )
        self.assertEqual(product.sku, f'MM-{product.pk}')
        product.name = 'Casco de prueba editado'
        product.save()
        product.refresh_from_db()
        self.assertEqual(product.sku, f'MM-{product.pk}')

    def test_custom_sku_is_kept(self):
        product = Product.objects.create(
            name='Guantes',
            sku='GTX-001',
            short_description='Guantes',
            description='Guantes',
            category=self.category,
            price=30000,
        )
        self.assertEqual(product.sku, 'GTX-001')

    def test_changing_current_cost_does_not_require_historical_recalc(self):
        """El costo vigente es solo catálogo; el snapshot histórico vive en la línea (Incremento 2)."""
        product = Product.objects.create(
            name='Mica',
            short_description='Mica',
            description='Mica',
            category=self.category,
            price=20000,
            cost_net=Decimal('8000'),
        )
        original = product.cost_net
        product.cost_net = Decimal('12000')
        product.save(update_fields=['cost_net'])
        product.refresh_from_db()
        self.assertEqual(original, Decimal('8000'))
        self.assertEqual(product.cost_net, Decimal('12000'))
