"""
Django settings for motomoto project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Cargar variables de entorno desde .env si existe
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-%3m5+&7_ens!u3db*_e4w*iz@em9em0++%0y__5bqa(c7jn6vh')

# SECURITY WARNING: don't run with debug turned on in production!
# En desarrollo local, forzar DEBUG=True para usar SQLite
# En Render, DEBUG se establece como 'False' en las variables de entorno
DEBUG_ENV = os.environ.get('DEBUG', 'True')
DEBUG = DEBUG_ENV == 'True'

# Detectar si estamos en Render (producción)
# Render monta el disco persistente en /opt/render/project/src/media
IS_RENDER = os.path.exists('/opt/render/project/src/media')

# Si estamos ejecutando comandos localmente (no en producción), forzar DEBUG=True
import sys
# Comandos que siempre deben usar SQLite en local (si no estamos en Render)
local_commands = ['runserver', 'loaddata', 'load_initial', 'load_initial_data', 'load_initial_products', 'clean_duplicate_images', 'clean_products', 'migrate', 'makemigrations', 'shell', 'createsuperuser', 'set_featured_products', 'set_product_prices', 'verify_images', 'fix_primary_images', 'load_products_from_json']
if any(cmd in sys.argv for cmd in local_commands) and not IS_RENDER:
    DEBUG = True

# Configuración de ALLOWED_HOSTS
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '').strip()

if ALLOWED_HOSTS_ENV:
    # Si se especifica en variables de entorno, usar esa configuración
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # En desarrollo, usar localhost
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    else:
        # En producción (Render), aceptar cualquier dominio .onrender.com
        # El formato .onrender.com acepta cualquier subdominio (ej: balu-c7hx.onrender.com)
        ALLOWED_HOSTS = ['.onrender.com', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir static files en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'motomoto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'motomoto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Usar PostgreSQL en producción (Render) o SQLite en desarrollo
# En desarrollo local (DEBUG=True o no estamos en Render), siempre usar SQLite
# En producción (Render con DEBUG=False), usar DATABASE_URL de Render
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL and IS_RENDER and not DEBUG:
    # En Render (producción), usar PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # En localhost (desarrollo), usar SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de WhiteNoise para servir static files en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'

# Configuración para disco persistente de Render
# El disco se monta en /opt/render/project/src/media
RENDER_DISK_PATH = '/opt/render/project/src/media'
if os.path.exists(RENDER_DISK_PATH):
    MEDIA_ROOT = Path(RENDER_DISK_PATH).resolve()
else:
    # En desarrollo local, usar el directorio del proyecto
    MEDIA_ROOT = (BASE_DIR / 'media').resolve()

# Crear directorio media y subdirectorio products si no existen
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
(MEDIA_ROOT / 'products').mkdir(parents=True, exist_ok=True)

# Convertir a string para compatibilidad con django.views.static.serve
MEDIA_ROOT = str(MEDIA_ROOT)

# Configuración de seguridad para producción
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# En desarrollo: mostrar emails en consola (para testing)
# En producción: usar SMTP con Gmail
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Producción: usar SMTP con Gmail
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Email para notificaciones de pedidos al administrador
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@motomoto.cl')

# =========================
# Mercado Pago (Checkout Pro)
# =========================
# Requeridos:
# - MP_ACCESS_TOKEN: token privado del vendedor (NO exponer en frontend)
# - MP_PUBLIC_KEY: llave pública (opcional si luego integras Bricks)
# - MP_BASE_URL: URL pública de tu sitio (ej: https://tu-dominio.com) para back_urls y webhooks
MP_ACCESS_TOKEN = os.environ.get('MP_ACCESS_TOKEN', '')
MP_PUBLIC_KEY = os.environ.get('MP_PUBLIC_KEY', '')
MP_BASE_URL = os.environ.get('MP_BASE_URL', '').rstrip('/')

# Opcional: URL pública fija para webhooks (si no quieres depender de MP_BASE_URL)
MP_WEBHOOK_URL = os.environ.get('MP_WEBHOOK_URL', '').strip()

# Nombre del método de pago en tu tabla PaymentMethod para activar el flujo de Mercado Pago
MP_PAYMENT_METHOD_NAME = os.environ.get('MP_PAYMENT_METHOD_NAME', 'Mercado Pago')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'shop.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
